"""Auto-generated collection reference for the system prompt.

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with: python -m data_agent.prompts.generate_collection_docs
"""

COLLECTION_REFERENCE = """\
=== AVAILABLE COLLECTIONS ===

- antibiotics: Chemical, pharmacological and mechanistic details for antibacterial agents used in AMR analytics and clinical-isolate annotation.
- bioset: Represents a contrast or set of statistically significant entities (genes, proteins, metabolites, etc.) derived from an experiment — typically a differential-expression list or time-point cluster.
- bioset_result: Stores per-entity quantitative results (counts, log2 FC, p-values, z-scores…) that belong to a bioset so BV-BRC can render volcano plots, heat maps and enrichment tables.
- enzyme_class_ref: Provides the authoritative mapping between EC numbers, their official textual descriptions, and corresponding GO terms, enabling enzyme look-ups and pathway annotation.
- epitope: Captures experimentally verified immune epitopes mapped to BV-BRC proteins, including sequence, host context, assay counts and taxonomy.
- epitope_assay: Holds detailed experimental assay records (B-cell, T-cell, MHC binding, etc.) linked to epitopes, with measurement values, host data and literature citations.
- experiment: High-level metadata for functional-omics experiments (transcriptomics, proteomics, metabolomics, etc.), linking them to biosets, genomes, treatments and publications.
- feature_sequence: Canonical raw sequence for every unique gene, RNA or protein encoded in BV-BRC genomes, keyed by MD5 for rapid identity checks and deduplication.
- gene_ontology_ref: Maps GO identifiers to names, definitions and ontology namespaces so BV-BRC can annotate features and run GO-term enrichment.
- genome: Rich sample, assembly and annotation metadata for every genome in BV-BRC, powering search, filters and downstream analyses across ∼1 M assemblies.
- genome_amr: Antimicrobial-resistance phenotype and/or genotype evidence linked to each genome, including lab methods, computational predictions and literature support.
- genome_feature: All annotated features—coding genes, RNAs, repeats—across BV-BRC genomes, with coordinates, functional annotation and family membership.
- genome_sequence: Every nucleotide replicon (chromosome, plasmid, contig, viral segment, etc.) associated with a genome, with sequence, quality metrics and ACL information.
- id_ref: Cross-walk table linking BV-BRC features to external identifier systems (NCBI GeneID, Ensembl, Pfam, etc.) for inter-database annotation and search.
- misc_niaid_sgc: Tracks gene/protein targets selected by the NIAID Structural Genomics Centers, indicating clone/protein availability and project status.
- pathway: Maps enzyme-encoding features in a genome to Pathway Tools / MetaCyc pathways, enabling metabolic reconstructions and presence/absence matrices.
- pathway_ref: Master lookup linking each EC activity to its position on curated pathway diagrams plus global occurrence counts for enrichment statistics.
- ppi: Pairwise protein–protein interaction metadata (detection methods, scores, literature) for network visualisation and comparative interactomics.
- protein_feature: Domain, motif, signal-peptide and other protein-level annotations identified in CDS translations, with coordinates and statistical scores.
- protein_family_ref: Lookup for every PATRIC protein-family accession (PGFam / PLFam) with descriptive name and namespace.
- protein_structure: Metadata and file pointers for every PDB entry mapped to BV-BRC genomes, including experimental details and chain-to-gene mappings.
- sequence_feature: Per-genome sequence features such as SNPs, indels or peptide motifs, linking them to canonical definitions, evidence codes and literature.
- sequence_feature_vt: Tracks each specific variant form of a canonical sequence feature across genomes, recording prevalence and variant sequences.
- serology: Laboratory serology results linked to host metadata and matching viral genomes, enabling antibody-prevalence and vaccine-impact studies.
- sp_gene: Lists antimicrobial-resistance, virulence and other “specialty” genes detected in genomes, with evidence metrics and curated classifications.
- sp_gene_ref: Master reference catalogue of specialty-gene alleles (AMR, virulence, toxins) with drug associations and literature support.
- spike_lineage: Month-by-month statistics for SARS-CoV-2 Pango lineages (growth, prevalence, VOC status) and their defining spike mutations.
- spike_variant: Monthly global statistics for notable SARS-CoV-2 spike-protein variants (D614G, etc.) including prevalence, growth rate and lineage diversity.
- strain: Per-strain metadata for segmented viruses (esp. influenza), linking segment accessions, host/geographic info and genome records.
- structured_assertion: Machine-readable statements about genomic features (e.g. “gene confers ciprofloxacin resistance”) with evidence codes and citations.
- subsystem: Links individual genes in a genome to SEED subsystems and roles, enabling subsystem heat-maps and completeness metrics.
- subsystem_ref: Reference hierarchy for SEED subsystems, including descriptions, literature and role lists.
- surveillance: Rich epidemiological, clinical and environmental metadata linking genomes to patient or wildlife surveillance information.
- taxonomy: NCBI lineage metadata plus genome-derived statistics (genome count, GC content, etc.) for every taxonomic node represented in BV-BRC.

=== COLLECTION FIELD REFERENCE ===

Below are the queryable fields for each collection. Use ONLY these field names in your Solr queries. If a field is not listed for a collection, it does NOT exist there -- do not guess or assume fields exist across collections.

[antibiotics]  (primary key: pubchem_cid)
  antibiotic_name (string (case-insensitive)): Preferred, curated drug name
  atc_classification (string[]): WHO ATC code(s)
  canonical_smiles (string): Canonical SMILES
  cas_id (string): CAS registry number
  description (string[]): Concise overview sentences
  drugbank_interactions (string[]): Known drug–drug interaction partners
  inchi_key (string): 27-character InChIKey hash
  isomeric_smiles (string): Stereospecific SMILES
  mechanism_of_action (string[]): Mode-of-action statements
  molecular_formula (string): Hill-system formula
  molecular_weight (string): Average molecular mass (Da)
  pharmacological_classes (string[]): Broad therapeutic class labels
  pharmacology (string[]): Detailed ADME/Tox notes
  pubchem_cid  (string): Primary key: PubChem CID
  pubchem_cid_i (integer): Numeric copy of CID
  synonyms (string[] (case-insensitive)): Alternate & trade names

[bioset]  (primary key: bioset_id)
  additional_data (string[]): Supplementary file links
  additional_metadata (string[] (ci)): Extra free-text metadata
  analysis_group_1 (string (ci)): Label for group 1 in comparison
  analysis_group_2 (string (ci)): Label for group 2 in comparison
  analysis_method (string (ci)): Computational method
  bioset_criteria (string (ci)): Threshold rule
  bioset_description (string (ci)): Concise description
  bioset_id (string): Primary key
  bioset_name (string (ci)): Short display name
  bioset_result (string[]): Linked result row IDs
  bioset_type (string (ci)): Category of bioset
  entity_count (string (ci)): Number of entities
  entity_type (string (ci)): Kind of entity
  exp_id (string): Parent experiment ID
  exp_name (string (ci)): Experiment name
  exp_title (string (ci)): Experiment title
  exp_type (string (ci)): Assay technology
  genome_id (string[]): Genome IDs analysed
  organism (string (ci)): Organism name
  protocol (string[]): Analysis/proc. steps
  result_type (string (ci)): Nature of metric
  strain (string (ci)): Strain designation
  study_description (string (ci)): Study abstract
  study_institution (string (ci)): Performing institution
  study_name (string (ci)): Study project label
  study_pi (string (ci)): Principal investigator
  study_title (string (ci)): Full study title
  taxon_id (integer): NCBI Taxonomy ID
  taxon_lineage_ids (string[]): Lineage ID chain
  treatment_amount (string (ci)): Dose or concentration
  treatment_duration (string (ci)): Exposure time
  treatment_name (string (ci)): Treatment label
  treatment_type (string (ci)): Treatment category

[enzyme_class_ref]  (primary key: ec_number)
  ec_description (string): Recommended enzyme name
  ec_number (string): EC four-level code
  go (string[] (ci)): Gene Ontology terms

[epitope]  (primary key: epitope_id)
  assay_results (string[]): Composite assay outcome strings
  bcell_assays (string): Count of B-cell assays
  comments (string[] (ci)): Curator comments
  end (integer): Epitope end position
  epitope_id (string): Primary key
  epitope_sequence (string): Sequence string
  epitope_type (string): Molecular type
  host_name (string[] (ci)): Host species tested
  mhc_assays (string): Count of MHC-binding assays
  organism (string (ci)): Source organism
  protein_accession (string): INSDC protein accession
  protein_id (string): BV-BRC feature ID
  protein_name (string (ci)): Protein product name
  start (integer): Epitope start position
  taxon_id (integer): NCBI Taxonomy ID
  taxon_lineage_ids (string[]): Lineage IDs
  taxon_lineage_names (string[]): Lineage names
  tcell_assays (string): Count of T-cell assays
  total_assays (integer): Total assay count

[epitope_assay]  (primary key: assay_id)
  assay_group (string): Logical assay grouping key
  assay_id (string): Primary key
  assay_measurement (string): Reported numeric value
  assay_measurement_unit (string): Unit of measurement
  assay_method (string): Experimental method
  assay_result (string): Qualitative outcome
  assay_type (string): Immunological assay class
  authors (string): First author + “et al.”
  end (integer): Epitope end position
  epitope_id (string): Linked epitope identifier
  epitope_sequence (string): Epitope sequence string
  epitope_type (string): Molecular type of epitope
  host_name (string (ci)): Experimental host species
  host_taxon_id (string): NCBI taxon ID for host
  mhc_allele (string): MHC allele tested
  mhc_allele_class (string): MHC class
  organism (string (ci)): Pathogen name
  pdb_id (string): PDB structure accession
  pmid (string): PubMed ID
  protein_accession (string): INSDC/RefSeq protein accession
  protein_id (string): BV-BRC feature ID
  protein_name (string (ci)): Protein product name
  start (integer): Epitope start position
  taxon_id (integer): Pathogen NCBI taxon ID
  taxon_lineage_ids (string[]): Lineage ID chain
  taxon_lineage_names (string[]): Lineage name chain
  title (string (ci)): Article or assay title

[experiment]  (primary key: exp_id)
  additional_data (string[]): Supplementary data links
  additional_metadata (string[] (ci)): Extra free-text metadata
  biosets (integer): Number of biosets
  detection_instrument (string (ci)): Instrument model
  doi (string): Digital Object Identifier
  exp_description (string (ci)): Concise experiment summary
  exp_id (string): Primary key
  exp_name (string (ci)): Short label
  exp_poc (string (ci)): Point-of-contact
  exp_protocol (string[] (ci)): Protocol steps
  exp_title (string (ci)): Full experiment title
  exp_type (string (ci)): Assay technology
  experimenters (string (ci)): Researcher list
  genome_id (string[]): BV-BRC genome IDs
  measurement_technique (string (ci)): Measurement platform
  organism (string[] (ci)): Organism names
  pmid (string): PubMed ID
  public_identifier (string): External ID
  public_repository (string): Repository name
  samples (integer): Number of biological samples
  strain (string[] (ci)): Strain names
  study_description (string (ci)): Study-level summary
  study_institution (string (ci)): Performing institution
  study_name (string (ci)): Study short name
  study_pi (string (ci)): Principal investigator
  study_title (string (ci)): Full study title
  taxon_id (integer[]): Taxonomy IDs
  taxon_lineage_ids (string[]): Lineage IDs
  treatment_amount (string[] (ci)): Dose/concentration
  treatment_duration (string[] (ci)): Exposure time
  treatment_name (string[] (ci)): Treatment label
  treatment_type (string[] (ci)): Treatment category

[feature_sequence]  (primary key: md5)
  md5 (string): MD5 hash of the sequence
  sequence (string): Raw nucleotide or amino-acid sequence
  sequence_type (string): Molecule type

[gene_ontology_ref]  (primary key: go_id)
  definition (string): Official GO definition sentence
  go_id (string): Gene Ontology accession
  go_name (string): Term name
  ontology (string): GO namespace

[genome]  (primary key: genome_id)
  additional_metadata (string[] (case-insensitive)): Miscellaneous key-value notes
  altitude (string): Sample altitude
  antimicrobial_resistance (string[] (case-insensitive)): Reported AMR phenotypes
  antimicrobial_resistance_evidence (string): Source of AMR call
  assembly_accession (string): GenBank / RefSeq assembly ID
  assembly_method (string (case-insensitive)): Software / pipeline used
  authors (string (case-insensitive)): Publication author list
  bioproject_accession (string): NCBI BioProject ID
  biosample_accession (string): NCBI BioSample ID
  biovar (string (case-insensitive)): Biovar designation
  body_sample_site (string (case-insensitive)): Anatomical site
  body_sample_subsite (string (case-insensitive)): Anatomical sub-site
  cds (integer): Number of CDS
  cds_ratio (number): CDS per kb ratio
  cell_shape (string (case-insensitive)): Cell morphology
  checkm_completeness (number): CheckM completeness (%)
  checkm_contamination (number): CheckM contamination (%)
  chromosomes (integer): Number of chromosomes
  city (string (case-insensitive)): City of isolation
  clade (string): Sub-species clade label
  class (string (case-insensitive)): Taxonomic class
  coarse_consistency (number): RAST QA score — coarse
  collection_date (string): Sample collection date
  collection_year (integer): Year of collection
  comments (string[] (case-insensitive)): Free-text curator notes
  common_name (string): Vernacular organism name
  completion_date (date): Assembly completion date
  contig_l50 (integer): L50 contig count
  contig_n50 (integer): N50 contig length (bp)
  contigs (integer): Total contig count
  core_families (integer): Core PGFam count
  core_family_ratio (number): Core family fraction
  county (string (case-insensitive)): County / district
  culture_collection (string (case-insensitive)): Culture collection ID(s)
  depth (string (case-insensitive)): Sampling depth
  disease (string[] (case-insensitive)): Associated disease(s)
  family (string (case-insensitive)): Taxonomic family
  fine_consistency (number): RAST QA score — fine
  gc_content (number): GC percentage
  genbank_accessions (string (case-insensitive)): Sequence accession list
  genome_id (string): Primary key
  genome_length (integer): Total assembly length (bp)
  genome_name (string (case-insensitive)): Scientific name + strain
  genome_quality (string): Quality tier
  genome_quality_flags (string[]): QC flag list
  genome_status (string (case-insensitive)): Assembly status
  genus (string (case-insensitive)): Taxonomic genus
  geographic_group (string (case-insensitive)): Regional grouping
  geographic_location (string (case-insensitive)): Free-text location
  gram_stain (string (case-insensitive)): Gram reaction
  h1_clade_global (string[]): Global H1 HA clade calls
  h1_clade_us (string[]): U.S. swine-flu H1 clades
  h3_clade (string[]): H3 HA clade calls
  h5_clade (string[]): H5 HA clade calls
  h_type (integer): HA subtype number
  habitat (string): Environmental habitat
  host_age (string): Host age
  host_common_name (string): Host common name
  host_gender (string): Host sex
  host_group (string): Host group category
  host_health (string): Host health state
  host_name (string): Original host field
  host_scientific_name (string): Host Latin name
  hypothetical_cds (integer): Count of “hypothetical protein” CDS
  hypothetical_cds_ratio (number): Fraction of CDS hypothetical
  isolation_comments (string): Isolation notes
  isolation_country (string): Country of origin
  isolation_site (string): Exact isolation site
  isolation_source (string): Material or substrate
  kingdom (string): Taxonomic kingdom
  lab_host (string): Laboratory propagation host
  latitude (string): Latitude of collection
  lineage (string): Viral or strain lineage
  longitude (string): Longitude of collection
  mat_peptide (integer): Mature peptide count
  missing_core_family_ids (string[]): Absent core PGFam IDs
  mlst (string): MLST type
  motility (string): Motility phenotype
  n_type (integer): NA subtype number
  ncbi_project_id (string): NCBI Genome Project ID
  nearest_genomes (string[]): Closest genome IDs
  optimal_temperature (string): Optimum growth temp
  order (string): Taxonomic order
  organism_name (string): Alternative organism name
  other_clinical (string[]): Additional clinical tags
  other_environmental (string[]): Misc. environmental tags
  other_names (string[]): Synonyms & historic names
  other_typing (string[]): Non-standard typing results
  outgroup_genomes (string[]): Outgroup genome IDs
  oxygen_requirement (string): Oxygen requirement
  p2_genome_id (integer): Legacy PATRIC2 ID
  partial_cds (integer): Incomplete CDS count
  partial_cds_ratio (number): Fraction CDS partial
  passage (string): Passage history
  pathovar (string): Pathovar name
  patric_cds (integer): CDS count (BV-BRC annotation)
  ph1n1_like (string): 2009 pH1N1 lineage flag
  phenotype (string[]): Recorded phenotypes
  phylum (string): Taxonomic phylum
  plasmids (integer): Plasmid count
  plfam_cds (integer): CDS with PLFam assignment
  plfam_cds_ratio (number): Fraction CDS in PLFam
  publication (string): Primary citation
  reference_genome (string): Reference flag
  refseq_accessions (string): RefSeq accession list
  refseq_cds (integer): CDS count (RefSeq)
  refseq_project_id (string): RefSeq project
  rrna (integer): rRNA gene count
  salinity (string): Salinity of environment
  season (string): Epidemiological season
  segment (string): Viral segment ID
  segments (integer): Number of segments
  sequencing_centers (string): Sequencing center(s)
  sequencing_depth (string): Average coverage
  sequencing_platform (string): Sequencing platform
  sequencing_status (string): Project status
  serovar (string): Serovar designation
  species (string): Taxonomic species
  sporulation (string): Sporulation ability
  sra_accession (string): SRA run or experiment ID
  state_province (string): State / province
  strain (string): Strain name
  subclade (string): Sub-clade label
  subtype (string): Viral subtype
  superkingdom (string): Top taxonomic rank
  taxon_id (integer): NCBI Taxonomy ID
  taxon_lineage_ids (string[]): Full lineage IDs
  taxon_lineage_names (string[]): Full lineage names
  temperature_range (string): Growth temperature range
  trna (integer): tRNA gene count
  type_strain (string): Type-strain flag

[genome_amr]  (primary key: id)
  antibiotic (string): Drug name tested
  computational_method (string (case-insensitive)): Name of the in-silico prediction tool
  computational_method_performance (string): Reported performance metrics
  computational_method_version (string): Version of the tool/database
  evidence (string (case-insensitive)): Evidence type
  genome_id (string): Parent genome identifier
  genome_name (string (case-insensitive)): Parent genome name
  id (string): Primary key
  laboratory_typing_method (string (case-insensitive)): Wet-lab test name
  laboratory_typing_method_version (string): Kit / panel version
  laboratory_typing_platform (string (case-insensitive)): Instrument platform
  measurement (string): Reported test value
  measurement_sign (string): Comparator
  measurement_unit (string): Unit for measurement
  measurement_value (string): Numeric value (as string)
  pmid (integer[]): PubMed IDs
  resistant_phenotype (string): Categorical result
  source (string (case-insensitive)): Data source
  taxon_id (integer): NCBI Taxonomy ID
  testing_standard (string (case-insensitive)): Standard/guideline
  testing_standard_year (integer): Year/version of standard
  vendor (string (case-insensitive)): Test-kit vendor

[genome_feature]  (primary key: feature_id)
  aa_length (integer): Protein length (aa)
  aa_sequence_md5 (string): MD5 of AA sequence
  accession (string): External accession
  alt_locus_tag (string): Alternate locus tag
  annotation (string): Source annotation pipeline
  brc_id (string): BV-BRC numeric ID
  classifier_round (integer): ML classifier round
  classifier_score (number): ML prediction score
  codon_start (integer): Translation start frame
  end (integer): End coordinate
  feature_id (string): Primary key
  feature_type (string): Feature class
  figfam_id (string): FIGfam identifier
  gene (string (ci)): Gene symbol
  gene_id (number): RefSeq gene ID
  genome_id (string): Parent genome ID
  genome_name (string (ci)): Parent genome name
  go (string[] (ci)): GO terms
  location (string): Contig-based location
  na_length (integer): Nucleotide length (bp)
  na_sequence_md5 (string): MD5 of NA sequence
  notes (string[]): Curator notes
  og_id (string): Ortholog group ID
  p2_feature_id (number): Legacy PATRIC2 ID
  patric_id (string): Redundant BV-BRC ID
  pdb_accession (string[]): 3D structure IDs
  pgfam_id (string): PGFam identifier
  plfam_id (string): PLFam identifier
  product (string (ci)): Functional product name
  property (string[]): Feature qualifiers
  protein_id (string): Protein accession
  refseq_locus_tag (string): RefSeq locus tag
  segments (string[]): Multi-segment coords
  sequence_id (string): Replicon ID
  sog_id (string): Sub-ortholog group ID
  start (integer): Start coordinate
  strand (string): Strand
  taxon_id (integer): NCBI Taxonomy ID
  uniprotkb_accession (string): UniProtKB ID

[genome_sequence]  (primary key: sequence_id)
  accession (string): Primary INSDC accession
  chromosome (string (ci)): Chromosome name/ID
  description (string (ci)): Replicon definition line
  gc_content (number): GC percentage
  genome_id (string): Parent genome identifier
  genome_name (string (ci)): Parent genome name
  gi (integer): Legacy NCBI GI number
  length (integer): Sequence length (bp/nt)
  mol_type (string (ci)): Molecule type
  p2_sequence_id (integer): Legacy PATRIC2 ID
  plasmid (string (ci)): Plasmid name
  release_date (date): Public release date
  segment (string (ci)): Viral segment ID
  sequence (string): Raw nucleotide sequence
  sequence_id (string): Primary key
  sequence_md5 (string): MD5 checksum
  sequence_status (string): Assembly status
  sequence_type (string (ci)): Replicon category
  taxon_id (integer): NCBI Taxonomy ID
  topology (string (ci)): DNA topology

[id_ref]  (primary key: id)
  id (string): Primary key
  id_type (string): Type of external identifier
  id_value (string): External identifier value
  uniprotkb_accession (string): UniProtKB accession

[misc_niaid_sgc]  (primary key: target_id)
  gene_symbol_collection (string[]): Gene symbols associated with the target
  genus (string): Genus name of source organism
  has_clones (string): Clone availability flag
  has_proteins (string): Purified-protein availability flag
  selection_criteria (string): Target-selection rationale
  species (string): Full species name
  strain (string): Strain / isolate designation
  target_id (string): Primary key (SGC target accession)
  target_status (string): Pipeline status

[pathway]  (primary key: id)
  accession (string (ci)): Replicon or contig accession
  alt_locus_tag (string): Alternate locus tag
  annotation (string (ci)): Annotation source
  ec_description (string (ci)): Enzyme name
  ec_number (string): EC number
  feature_id (string): Gene/feature identifier
  gene (string (ci)): Gene symbol
  genome_ec (string): “Genome-EC” composite
  genome_id (string): Parent genome identifier
  genome_name (string (ci)): Parent genome name
  id (string): Primary key
  pathway_class (string (ci)): Broad pathway class
  pathway_ec (string): “Pathway-EC” composite
  pathway_id (string): MetaCyc/Pathway Tools ID
  pathway_name (string (ci)): Pathway display name
  patric_id (string): Redundant feature alias
  product (string (ci)): Protein product name
  refseq_locus_tag (string): RefSeq locus tag
  sequence_id (string): Replicon ID
  taxon_id (integer): NCBI Taxonomy ID

[pathway_ref]  (primary key: id)
  ec_description (string): Enzyme display name
  ec_number (string): EC four-level code
  id (string): Primary key
  map_location (string[]): Pathway-map co-ordinates
  map_name (string): Graphic map filename
  map_type (string): Map provenance
  occurrence (integer): Genome occurrence count
  pathway_class (string): High-level pathway class
  pathway_id (string): Pathway identifier
  pathway_name (string): Human-readable pathway name

[ppi]  (primary key: id)
  category (string): Interaction category
  detection_method (string[] (ci)): Interaction-detection methods
  domain_a (string): Interacting domain A
  domain_b (string): Interacting domain B
  evidence (string[]): Evidence statements
  feature_id_a (string): BV-BRC feature ID A
  feature_id_b (string): BV-BRC feature ID B
  gene_a (string): Gene symbol A
  gene_b (string): Gene symbol B
  genome_id_a (string): Genome ID A
  genome_id_b (string): Genome ID B
  genome_name_a (string (ci)): Genome name A
  genome_name_b (string (ci)): Genome name B
  id (string): Primary key
  interaction_type (string[] (ci)): Nature of interaction
  interactor_a (string): Primary accession A
  interactor_b (string): Primary accession B
  interactor_desc_a (string (ci)): Product name A
  interactor_desc_b (string (ci)): Product name B
  interactor_type_a (string): Entity type A
  interactor_type_b (string): Entity type B
  pmid (string[]): PubMed IDs
  refseq_locus_tag_a (string): RefSeq tag A
  refseq_locus_tag_b (string): RefSeq tag B
  score (string[]): Confidence / weight
  source_db (string[]): Source database(s)
  source_id (string[]): Source-specific IDs
  taxon_id_a (integer): Taxon ID A
  taxon_id_b (integer): Taxon ID B

[protein_feature]  (primary key: id)
  aa_sequence_md5 (string): MD5 hash of the full protein sequence
  classification (string[]): Category tags for the feature
  comments (string[] (ci)): Curator or tool comments
  description (string (ci)): Hit description from source DB
  e_value (string): Expect value of the match
  end (integer): End position (aa)
  evidence (string): Evidence phrase
  feature_id (string): Parent gene/feature ID
  feature_type (string): Type of parent feature
  gene (string): Gene symbol
  genome_id (string): Parent genome identifier
  genome_name (string (ci)): Parent genome name
  id (string): Primary key
  interpro_description (string (ci)): InterPro family description
  interpro_id (string): InterPro accession
  length (integer): Feature length (aa)
  patric_id (string): Alias of feature_id
  product (string (ci)): Protein product name
  publication (string[]): Supporting literature
  refseq_locus_tag (string): RefSeq locus tag
  score (number): Raw alignment score
  segments (string[]): Multi-segment coordinates
  sequence (string): Domain peptide sequence
  source (string): Source database
  source_id (string): Accession in source DB
  start (integer): Start position (aa)
  taxon_id (integer): NCBI Taxonomy ID

[protein_family_ref]  (primary key: family_id)
  family_id (string): Protein-family identifier
  family_product (string): Canonical family product name
  family_type (string): Family namespace

[protein_structure]  (primary key: pdb_id)
  alignments (string[]): Alignment identifiers or paths
  authors (string[]): Publication authors
  feature_id (string): BV-BRC gene/feature ID
  file_path (string): Object-store path
  gene (string[]): Gene symbol(s)
  genome_id (string): Parent genome ID
  institution (string): Depositing institution
  method (string[]): Experimental method(s)
  organism_name (string[] (ci)): Organism(s)
  patric_id (string): Alias of feature_id
  pdb_id (string): Primary key (PDB accession)
  pmid (string[]): PubMed IDs
  product (string[]): Protein product names
  release_date (date): PDB release date
  resolution (string): Experimental resolution
  sequence (string[]): Protein sequence(s)
  sequence_md5 (string[]): MD5 of each sequence
  taxon_id (integer[]): Taxon IDs per chain
  taxon_lineage_ids (string[]): Lineage IDs
  taxon_lineage_names (string[]): Lineage names
  title (string (ci)): Structure title
  uniprotkb_accession (string[]): UniProtKB IDs

[sequence_feature]  (primary key: id)
  aa_sequence_md5 (string): MD5 hash of the AA sequence after variation
  aa_variant (string): HGVS-style AA change
  additional_metadata (string[] (ci)): Extra free-text tags
  comments (string[] (ci)): Curator / caller notes
  end (integer): End coordinate
  evidence_code (string): Variant evidence code
  feature_id (string): Parent gene/feature ID
  genbank_accession (string): INSDC accession of source contig
  gene (string): Gene symbol
  genome_id (string): BV-BRC genome identifier
  genome_name (string (ci)): Genome display name
  id (string): Primary key
  length (integer): Length of the observed SF
  patric_id (string): Alias of feature_id
  product (string (ci)): Protein product
  publication (string[]): Supporting literature
  refseq_locus_tag (string): RefSeq locus tag
  segment (string): Viral segment
  segments (string[]): Multi-segment coords
  sf_category (string): Sequence-feature category
  sf_id (string): Sequence-feature ID
  sf_name (string (ci)): Human-readable name
  sf_sequence (string): Observed variant sequence
  sf_sequence_md5 (string): MD5 of sf_sequence
  source (string): Calling pipeline / DB
  source_aa_sequence (string): Peptide context
  source_id (string): External source key
  source_sf_location (string): Location in source coords
  source_strain (string): Strain name from source
  start (integer): Start coordinate
  subtype (string): Viral subtype
  taxon_id (integer): NCBI Taxonomy ID
  variant_types (string): HGVS variant codes

[sequence_feature_vt]  (primary key: id)
  additional_metadata (string[] (case-insensitive)): Extra free-text key-value pairs
  comments (string[] (case-insensitive)): Curator notes
  id (string): Primary key
  sf_category (string): Category of sequence feature
  sf_id (string): Canonical sequence-feature ID
  sf_name (string (case-insensitive)): Canonical feature name
  sf_sequence (string): Canonical feature sequence
  sf_sequence_md5 (string): MD5 of sf_sequence
  sfvt_genome_count (string): Number of genomes with this variant
  sfvt_genome_ids (string[]): Genomes carrying this variant
  sfvt_id (string): Variant-tracking ID
  sfvt_sequence (string): Variant sequence
  sfvt_sequence_md5 (string): MD5 of variant sequence
  sfvt_variations (string): HGVS or descriptive change

[serology]  (primary key: id)
  additional_metadata (string[] (ci)): Free-text key-value notes
  collection_city (string (ci)): City / town of collection
  collection_country (string (ci)): Country name (ISO)
  collection_date (date): Date sample taken
  collection_state (string (ci)): State / province
  collection_year (string (ci)): Four-digit year (text)
  comments (string[] (ci)): Curator comments
  contributing_institution (string (ci)): Data provider
  genbank_accession (string[] (ci)): Related GenBank accessions
  geographic_group (string (ci)): Regional bucket
  host_age (string (ci)): Exact age / range
  host_age_group (string (ci)): Age-group bin
  host_common_name (string (ci)): Common host name
  host_health (string (ci)): Health status
  host_identifier (string): De-identified host ID
  host_sex (string (ci)): Sex of host
  host_species (string (ci)): Scientific name
  host_type (string[] (ci)): Host class/category
  id (string): Primary key
  positive_definition (string (ci)): Positivity cut-off rule
  project_identifier (string): Study / project code
  sample_accession (string): Public repository accession
  sample_identifier (string): Local sample ID
  sample_material (string (ci)): Matrix tested
  sample_receipt_date (string (ci)): Date lab received sample
  sample_transport_medium (string (ci)): Medium used
  sequence_accession (string[]): Linked sequence IDs
  source_of_vaccine_information (string[] (ci)): Provenance of vax data
  species (string (ci)): Virus species
  strain (string (ci)): Viral strain antigen
  taxon_lineage_ids (string[]): Viral lineage IDs
  test_antigen (string (ci)): Antigen target
  test_interpretation (string (ci)): Overall result
  test_pathogen (string (ci)): Pathogen tested
  test_result (string (ci)): Numeric / categorical result
  test_type (string (ci)): Assay method
  virus_identifier (string (ci)): Virus identifier used in lab

[sp_gene]  (primary key: id)
  alt_locus_tag (string): Alternate locus tag
  antibiotics (string[]): Affected antibiotics
  antibiotics_class (string): Drug class
  classification (string[]): Gene family / category
  e_value (string): BLAST/DIAMOND E-value
  evidence (string): Evidence statement
  feature_id (string): Gene/feature identifier
  function (string): Functional annotation
  gene (string): Gene symbol
  genome_id (string): Parent genome ID
  genome_name (string): Parent genome name
  id (string): Primary key
  identity (integer): % identity
  organism (string): Source organism of ref allele
  patric_id (string): Alias of feature_id
  pmid (string[]): PubMed IDs
  product (string): Protein product name
  property (string): Specialty-gene property
  property_source (string): Source database
  query_coverage (integer): % query coverage
  refseq_locus_tag (string): RefSeq locus tag
  same_genome (integer): Intra-genome hits
  same_genus (integer): Hit count in genus
  same_species (integer): Hit count in species
  source (string): Curation source
  source_id (string): Source database ID
  subject_coverage (integer): % subject coverage
  taxon_id (integer): NCBI Taxonomy ID

[sp_gene_ref]  (primary key: id)
  antibiotics (string[]): Antibiotics affected
  antibiotics_class (string): Drug class
  assertion (string): Curatorial assertion
  classification (string[]): Functional categories
  function (string): Functional description
  gene_id (string): Reference-sequence ID
  gene_name (string): Gene symbol
  genus (string): Typical genus host
  gi (string): Legacy NCBI GI number
  id (string): Primary key
  locus_tag (string): Locus tag
  organism (string): Source organism
  pmid (string[]): PubMed IDs
  product (string): Protein product
  property (string): Specialty-gene property
  source (string): External database
  source_id (string): Source database ID
  species (string): Typical species host

[spike_lineage]  (primary key: id)
  country (string (ci)): Country with highest prevalence for this lineage in the reporting month
  growth_rate (number): Week-over-week growth factor
  id (string): Primary key
  lineage (string): Pango/WHO lineage designation
  lineage_count (integer): Number of sub-lineages collapsed into this record for month
  lineage_of_concern (string): VOC/VBM status
  month (string): Reporting month
  prevalence (number): Percentage of worldwide isolates in month that belong to this lineage
  region (string (ci)): WHO/CDC broad region
  sequence_features (string[]): Defining mutations’ sf_id list
  total_isolates (integer): Total genomes analysed for the month

[spike_variant]  (primary key: id)
  aa_variant (string): Amino-acid change(s) that define the spike variant
  country (string (ci)): Country with highest prevalence during the reporting month
  growth_rate (number): Estimated week-over-week growth rate
  id (string): Primary key
  lineage_count (integer): Number of distinct Pango lineages carrying this variant in the given month
  month (string): Reporting month
  prevalence (number): Percentage of worldwide isolates in month that carry aa_variant
  region (string (ci)): WHO/CDC broad region
  sequence_features (string[]): Associated sequence-feature IDs
  total_isolates (integer): Total number of genomes analysed for the month

[strain]  (primary key: id)
  1_pb2 (string[]): PB2 segment GenBank accessions
  2_pb1 (string[]): PB1 segment accessions
  3_pa (string[]): PA segment accessions
  4_ha (string[]): HA segment accessions
  5_np (string[]): NP segment accessions
  6_na (string[]): NA segment accessions
  7_mp (string[]): MP segment accessions
  8_ns (string[]): NS segment accessions
  collection_date (string): Sampling date (raw)
  collection_year (integer): Sampling year
  family (string (ci)): Taxonomic family
  genbank_accessions (string[]): All segment accessions
  genome_ids (string[]): Linked BV-BRC genome_id(s)
  genus (string (ci)): Taxonomic genus
  geographic_group (string (ci)): Regional grouping
  h_type (integer): HA subtype number
  host_common_name (string (ci)): Host common name
  host_group (string (ci)): Host class
  host_name (string (ci)): Raw host field
  id (string): Primary key
  isolation_country (string (ci)): Country of origin
  l (string[]): Large (L) segment IDs
  lab_host (string (ci)): Propagation host
  m (string[]): Medium (M) segment IDs
  n_type (integer): NA subtype number
  other_segments (string[]): Non-canonical segment IDs
  passage (string (ci)): Passage history
  s (string[]): Small (S) segment IDs
  season (string): Epidemiological season
  segment_count (integer): Number of segments
  species (string (ci)): Taxonomic species
  status (string): QC / release status
  strain (string (ci)): Strain name
  subtype (string): Viral subtype
  taxon_id (integer): NCBI Taxonomy ID
  taxon_lineage_ids (string[]): Full lineage IDs
  taxon_lineage_names (string[]): Full lineage names

[structured_assertion]  (primary key: id)
  comment (string): Curator comment
  evidence_code (string): Evidence code
  feature_id (string): BV-BRC feature ID
  id (string): Primary key
  patric_id (string): Alias of feature_id
  pmid (string): PubMed ID
  property (string): Assertion property
  refseq_locus_tag (string): RefSeq locus tag
  score (string): Confidence / weight
  source (string): Origin of assertion
  value (string): Assertion value

[subsystem]  (primary key: id)
  active (string): Subsystem presence flag
  class (string): Subsystem class
  feature_id (string): Gene/feature identifier
  gene (string): Gene symbol
  genome_id (string): Parent genome identifier
  genome_name (string (case-insensitive)): Parent genome name
  id (string): Primary key
  patric_id (string): Alias of feature_id
  product (string): Protein product name
  refseq_locus_tag (string): NCBI locus tag
  role_id (string): Subsystem role identifier
  role_name (string): Functional role name
  subclass (string): Subsystem subclass
  subsystem_id (string): Subsystem identifier
  subsystem_name (string): Subsystem name
  superclass (string): Super-class
  taxon_id (integer): NCBI Taxonomy ID

[subsystem_ref]  (primary key: id)
  class (string): First-tier subsystem class
  description (string): Subsystem description
  id (string): Primary key
  notes (string[]): Curator notes
  pmid (string[]): PubMed IDs
  role_id (string[]): Role identifier list
  role_name (string[]): Functional role names
  subclass (string): Second-tier category
  subsystem_id (string): SEED subsystem ID
  subsystem_name (string): Display name
  superclass (string): Top-level grouping

[surveillance]  (primary key: id)
  additional_metadata (string[] (case-insensitive)): Arbitrary key–value notes
  alcohol_or_other_drug_dependence (string (ci)): Substance-dependence status of human host
  breastfeeding (string (ci)): Breast-feeding status
  chest_imaging_interpretation (string (ci)): Radiology result
  chronic_conditions (string[] (ci)): Pre-existing conditions
  collection_city (string (ci)): City/town where sample collected
  collection_country (string (ci)): ISO-name of country
  collection_date (date): Date of sample collection
  collection_latitude (number): GPS latitude
  collection_longitude (number): GPS longitude
  collection_poi (string (ci)): Point-of-interest descriptor
  collection_season (string (ci)): Epidemiological season
  collection_state_province (string (ci)): State / province
  collection_year (string (ci)): Four-digit year text
  collector_institution (string (ci)): Institution that took the sample
  collector_name (string[] (ci)): Names of collectors
  comments (string[] (ci)): Free-text remarks
  contact_email_address (string (ci)): Data contact email
  contributing_institution (string (ci)): Data-submitting organisation
  daycare_attendance (string (ci)): Child daycare attendance
  days_elapsed_to_disease_status (string (ci)): Days from exposure to symptom onset
  days_elapsed_to_sample_collection (string (ci)): Days from symptom onset to sampling
  days_elapsed_to_vaccination (string[] (ci)): Days between vaccination and sample
  diagnosis (string[] (ci)): Clinical diagnoses
  dialysis (string (ci)): Dialysis patient flag
  disease_severity (string (ci)): Severity classification
  disease_status (string (ci)): Case, contact, carrier, etc.
  duration_of_exposure (string[] (ci)): Exposure duration
  duration_of_treatment (string[] (ci)): Treatment course length
  ecmo (string (ci)): ECMO support flag
  education (string (ci)): Highest education level
  embargo_end_date (date): Data-release date
  exposure (string[] (ci)): Exposure descriptors
  exposure_type (string[] (ci)): Exposure category
  genome_id (string[]): Linked BV-BRC genome IDs
  geographic_group (string (ci)): Regional bucket
  hospitalization_duration (string (ci)): Length of hospital stay
  hospitalized (string (ci)): Hospital admission status
  host_age (string (ci)): Age or age-range
  host_capture_status (string (ci)): Capture outcome for wildlife
  host_common_name (string (ci)): Common name of host
  host_ethnicity (string[] (ci)): Ethnicity descriptors
  host_group (string (ci)): Broad host group
  host_habitat (string (ci)): Habitat type
  host_health (string (ci)): Health status at sampling
  host_height (string (ci)): Height of human host
  host_id_type (string (ci)): Identifier system
  host_identifier (string): Unique host ID
  host_natural_state (string (ci)): Captive or wild status
  host_race (string[] (ci)): Race classification
  host_sex (string (ci)): Sex of host
  host_species (string (ci)): Scientific species name
  host_weight (string (ci)): Weight with units
  human_leukocyte_antigens (string (ci)): HLA genotype summary
  id (string): Primary key
  infections_within_five_years (string[] (ci)): Prior infections (5-y look-back)
  influenza_like_illness_over_the_past_year (string (ci)): ILI flag
  initiation_of_treatment (string[] (ci)): Start date / time of therapy
  intensive_care_unit (string (ci)): ICU admission status
  last_update_date (date): Most recent record update
  longitudinal_study (string (ci)): Longitudinal flag
  maintenance_medication (string[] (ci)): Chronic medications
  nursing_home_residence (string (ci)): Nursing-home status
  onset_hours (string (ci)): Hours since symptom onset
  other_vaccinations (string (ci)): Non-targeted vaccines
  oxygen_saturation (string (ci)): SpO₂ at presentation
  packs_per_day_for_how_many_years (string (ci)): Smoking intensity
  pathogen_test_interpretation (string[] (ci)): Test interpretation
  pathogen_test_result (string[]): Raw test value
  pathogen_test_type (string[] (ci)): Diagnostic tests performed
  pathogen_type (string (ci)): Target pathogen class
  post_visit_medications (string[] (ci)): Drugs started after visit
  pre_visit_medications (string[] (ci)): Drugs taken before visit
  pregnancy (string (ci)): Pregnancy status
  primary_living_situation (string (ci)): Living arrangement
  profession (string (ci)): Occupation
  project_identifier (string): Study/project code
  sample_accession (string): Public repository accession
  sample_identifier (string): Local sample ID
  sample_material (string (ci)): Sample type
  sample_receipt_date (string (ci)): Date lab received sample
  sample_transport_medium (string (ci)): Medium used
  sequence_accession (string[]): Public sequence IDs
  source_of_vaccine_information (string[] (ci)): Vaccine data provenance
  species (string (ci)): Host species binomial
  strain (string (ci)): Pathogen strain name
  submission_date (date): Date row was submitted to BV-BRC
  subtype (string (ci)): Viral subtype
  sudden_onset (string (ci)): Sudden-onset symptom flag
  symptoms (string[] (ci)): Reported symptoms
  taxon_lineage_ids (string[]): NCBI lineage IDs
  tobacco_use (string (ci)): Smoking status
  travel_history (string[] (ci)): Recent travel descriptors
  treatment (string[] (ci)): Therapies applied
  treatment_dosage (string[] (ci)): Dose information
  treatment_type (string[] (ci)): Treatment modality
  trimester_of_pregnancy (string (ci)): Gestational stage
  types_of_allergies (string[] (ci)): Reported allergies
  use_of_personal_protective_equipment (string[] (ci)): PPE usage
  vaccination_type (string (ci)): Vaccine product
  vaccine_dosage (string[] (ci)): Dose amounts
  vaccine_lot_number (string[] (ci)): Batch numbers
  vaccine_manufacturer (string[] (ci)): Producer names
  ventilation (string (ci)): Mechanical ventilation

[taxonomy]  (primary key: taxon_id)
  cds_mean (number): Mean number of CDS per genome
  cds_sd (number): Standard deviation of CDS count
  core_families (integer): Count of core protein families
  core_family_ids (string[]): IDs of those core families
  description (string): NCBI Taxonomy description
  division (string): NCBI Taxonomy division code
  genetic_code (integer): NCBI genetic code
  genome_count (integer): Synonym of genomes
  genome_length_mean (number): Mean genome length (bp)
  genome_length_sd (number): Std. dev. of genome length
  genomes (integer): Total genomes in BV-BRC
  genomes_f (string): Formatted genome count
  hypothetical_cds_ratio_mean (number): Mean % hypothetical CDS
  hypothetical_cds_ratio_sd (number): Std. dev. of that ratio
  lineage (string): Textual lineage string
  lineage_ids (integer[]): Taxon IDs along lineage
  lineage_names (string[]): Names along lineage
  lineage_ranks (string[]): Rank words along lineage
  other_names (string[] (case-insensitive)): Synonyms & common names
  parent_id (integer): Immediate parent taxon ID
  plfam_cds_ratio_mean (number): Mean % CDS with a PLFam
  plfam_cds_ratio_sd (number): Std. dev. of that ratio
  taxon_id (string): Primary key (string copy)
  taxon_id_i (integer): Numeric copy of taxon ID
  taxon_name (string (case-insensitive)): Scientific name
  taxon_rank (string): Rank of the taxon
"""
