"""Auto-generated BV-BRC service reference for system prompt.

Generated by: python -m service_agent.prompts.generate_service_docs
Source: bvbrc-mcp-server/config/service_required_params.json
        bvbrc-mcp-server/config/service_mapping.json
"""

SERVICE_REFERENCE = """\
=== BV-BRC SERVICE REFERENCE ===

Total services: 31

--- Genomics ---

  genome_assembly (API: GenomeAssembly2)
    Description: Assemble genomes from sequencing reads (Illumina, PacBio, Nanopore)
    Required: output_path, output_file
    Required (at least one): paired_end_libs | single_end_libs | srr_ids
    Defaults: recipe=auto, racon_iter=2, pilon_iter=2, trim=False, normalize=False, min_contig_len=300, min_contig_cov=5, genome_size=5000000, debug=0
    Enum recipe: auto, unicycler, flye, meta-flye, canu, spades, meta-spades, plasmid-spades, single-cell, megahit

  genome_annotation (API: GenomeAnnotation)
    Description: Annotate assembled genomes with gene predictions and functional annotations
    Required: contigs, scientific_name, code, domain
    Required (at least one): contigs
    Defaults: code=0, domain=auto, public=False, queue_nowait=False, skip_indexing=False, skip_workspace_output=False
    Enum code: 0, 1, 4, 11, 25
    Enum domain: Bacteria, Archaea, Viruses, auto

  comprehensive_genome_analysis (API: ComprehensiveGenomeAnalysis)
    Description: Full pipeline: assembly, annotation, and quality analysis
    Required: input_type, output_path, output_file, scientific_name, code, domain
    Required (at least one): paired_end_libs | single_end_libs | srr_ids | reference_assembly | gto | genbank_file | contigs
    Defaults: recipe=auto, racon_iter=2, pilon_iter=2, trim=False, normalize=False, filtlong=False, target_depth=200, genome_size=5000000, min_contig_len=300, min_contig_cov=5, public=False, queue_nowait=False, skip_indexing=False, code=0, domain=auto, analyze_quality=False, debug_level=0
    Enum input_type: reads, contigs, genbank
    Enum platform: infer, illumina, pacbio, pacbio_hifi, nanopore
    Enum recipe: auto, unicycler, canu, spades, meta-spades, plasmid-spades, single-cell, flye
    Enum code: 0, 1, 4, 11, 25
    Enum domain: Bacteria, Archaea, Viruses, auto
    When input_type=reads: requires one of paired_end_libs | single_end_libs | srr_ids
    When input_type=contigs: requires one of contigs | reference_assembly
    When input_type=genbank: requires one of genbank_file | gto

  similar_genome_finder (API: SimilarGenomeFinder)
    Description: Find similar genomes in BV-BRC using Mash/MinHash

  genome_alignment (API: GenomeAlignment)
    Description: Align multiple genomes using Mauve
    Required: genome_ids, output_path, output_file
    Defaults: genome_ids=[], recipe=progressiveMauve
    Enum recipe: progressiveMauve, mauveAligner

--- Phylogenomics ---

  bacterial_genome_tree (API: CodonTree)
    Description: Build phylogenetic trees from bacterial genomes using codon trees
    Required: output_path, output_file
    Defaults: genome_ids=[], genome_groups=[], optional_genome_ids=[], number_of_genes=20, bootstraps=100, max_genomes_missing=0, max_allowed_dups=0

  gene_tree (API: GeneTree)
    Description: Build gene-level phylogenetic trees (RAxML, PhyML, FastTree)
    Required: sequences, alphabet, output_path, output_file
    Defaults: recipe=RAxML
    Enum alphabet: DNA, Protein
    Enum substitution_model: HKY85, JC69, K80, F81, F84, TN93, GTR, LG, WAG, JTT, MtREV, Dayhoff, DCMut, RtREV, CpREV, VT, AB, Blosum62, MtMam, MtArt, HIVw, HIVb
    Enum recipe: RAxML, PhyML, FastTree
    Enum tree_type: viral_genome, gene

  core_genome_mlst (API: CoreGenomeMLST)
    Description: Core genome MLST analysis using chewBBACA
    Required: input_genome_type, analysis_type, input_schema_selection, output_path, output_file
    Defaults: input_genome_type=genome_group, analysis_type=chewbbaca
    Enum input_genome_type: genome_group, genome_fasta
    Enum analysis_type: chewbbaca

  whole_genome_snp (API: WholeGenomeSNPAnalysis)
    Description: Whole genome SNP analysis for phylogenomics
    Required: input_genome_type, analysis_type, output_path, output_file
    Defaults: majority-threshold=0.5, min_mid_linkage=10, max_mid_linkage=40
    Enum input_genome_type: genome_group, genome_fasta
    Enum majority-threshold: 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1
    Enum analysis_type: Whole Genome SNP Analysis

--- Metagenomics ---

  taxonomic_classification (API: TaxonomicClassification)
    Description: Classify metagenomic reads taxonomically (Kraken2)
    Required: host_genome, analysis_type, database, save_classified_sequences, save_unclassified_sequences, confidence_interval, output_path, output_file
    Required (at least one): paired_end_libs | single_end_libs | srr_libs
    Defaults: host_genome=no_host, analysis_type=microbiome, database=bvbrc, save_classified_sequences=false, save_unclassified_sequences=false, confidence_interval=0.1
    Enum host_genome: homo_sapiens, mus_musculus, rattus_norvegicus, caenorhabditis_elegans, drosophila_melanogaster_strain, danio_rerio_strain_tuebingen, gallus_gallus, macaca_mulatta, mustela_putorius_furo, sus_scrofa, no_host
    Enum analysis_type: pathogen, microbiome, 16S
    Enum database: bvbrc, Greengenes, SILVA, standard

  metagenomic_binning (API: MetagenomeBinning)
    Description: Bin metagenomic assemblies into individual genomes
    Required: output_path, output_file, force_local_assembly
    Required (at least one): paired_end_libs | single_end_libs | srr_ids | contigs
    Defaults: skip_indexing=False, force_local_assembly=False, force_inline_annotation=True, perform_bacterial_binning=True, perform_viral_binning=False, perform_viral_annotation=False, perform_bacterial_annotation=True, assembler=, danglen=50, min_contig_len=400, min_contig_cov=4

  metagenomic_read_mapping (API: MetagenomicReadMapping)
    Description: Map metagenomic reads to gene sets (VFDB, CARD)
    Required: gene_set_type, output_path, output_file
    Required (at least one): paired_end_libs | single_end_libs | srr_ids
    Enum gene_set_type: predefined_list, fasta_file, feature_group
    Enum gene_set_name: VFDB, CARD, feature_group, fasta_file

  metacats (API: MetaCATS)
    Description: Metagenomic comparative analysis (MetaCATS)
    Required: output_path, output_file, p_value, input_type, alphabet
    Defaults: p_value=0.05, alphabet=na, groups=[]
    Enum input_type: auto, groups, files
    Enum alphabet: na, aa
    Enum alignment_type: aligned_dna_fasta, aligned_protein_fasta

--- Transcriptomics ---

  rnaseq (API: RNASeq)
    Description: RNA-Seq analysis with differential expression
    Required: reference_genome_id, genome_type, recipe, output_path, output_file
    Required (at least one): paired_end_libs | single_end_libs | srr_libs
    Defaults: strand_specific=True, recipe=HTSeq-DESeq, trimming=False
    Enum genome_type: bacteria, host
    Enum recipe: HTSeq-DESeq, cufflinks, Host

  expression_import (API: ExpressionImport)
    Description: Import gene expression datasets
    Required: xfile, ustring

--- Proteomics ---

  proteome_comparison (API: GenomeComparison)
    Description: Compare proteomes across genomes
    Required: output_path, output_file
    Defaults: reference_genome_index=1, min_seq_cov=0.3, max_e_val=1e-05, min_ident=0.1, min_positives=0.2

  docking (API: Docking)
    Description: Molecular docking analysis
    Required: protein_input_type, ligand_library_type, batch_size, output_path, output_file
    Defaults: batch_size=10

--- Variation Analysis ---

  variation (API: Variation)
    Description: SNP/variant calling from sequencing reads
    Required: reference_genome_id, output_path, output_file
    Required (at least one): paired_end_libs | single_end_libs | srr_ids
    Defaults: mapper=BWA-mem, caller=FreeBayes, debug=False
    Enum mapper: BWA-mem, BWA-mem-strict, Bowtie2, MOSAIK, LAST, minimap2
    Enum caller: FreeBayes, BCFtools

  msa_snp_analysis (API: MSA)
    Description: Multiple sequence alignment and SNP analysis
    Required: alphabet, output_path, output_file
    Defaults: input_status=, input_type=, aligner=Muscle, alphabet=dna, fasta_keyboard_input=, ref_type=none, strategy=auto, ref_string=
    Enum input_status: unaligned, aligned
    Enum input_type: input_group, input_fasta, input_sequence, input_genomegroup, input_featurelist, input_genomelist
    Enum aligner: Muscle, Mafft, progressiveMauve
    Enum alphabet: dna, protein
    Enum ref_type: none, string, feature_id, genome_id, first
    Enum strategy: auto, fftns1, fftns2, fftnsi, einsi, linsi, ginsi

--- Sequence Analysis ---

  blast (API: Homology)
    Description: BLAST sequence homology search
    Required: input_type, input_source, db_type, db_source, output_path, output_file
    Required (at least one): input_fasta_data | input_id_list | input_fasta_file | input_feature_group | input_genome_group
    Defaults: blast_evalue_cutoff=1e-05, blast_max_hits=300
    Enum input_type: dna, aa
    Enum input_source: id_list, fasta_data, fasta_file, feature_group, genome_group_features, genome_group_sequences
    Enum db_type: faa, ffn, frn, fna
    Enum db_source: id_list, fasta_data, fasta_file, genome_list, feature_group, genome_group, taxon_list, precomputed_database
    Enum blast_program: blastp, blastn, blastx, tblastn, tblastx
    When db_source=precomputed_database: requires db_precomputed_database
    When input_source=id_list: requires input_id_list
    When db_source=id_list: requires db_id_list

  primer_design (API: PrimerDesign)
    Description: Design PCR primers
    Required: output_file, output_path, input_type, sequence_input

  fastqutils (API: FastqUtils)
    Description: FASTQ quality control and preprocessing
    Required: output_path, output_file, recipe
    Required (at least one): paired_end_libs | single_end_libs | srr_libs
    Defaults: recipe=[]

--- Transposon Analysis ---

  tnseq (API: TnSeq)
    Description: Transposon insertion sequencing analysis
    Required: reference_genome_id, output_path, output_file
    Defaults: experimental_conditions=[], contrasts=[], recipe=gumbel, protocol=sassetti, primer=
    Enum recipe: gumbel, griffin, tn5gaps, rankproduct, hmm, binomial, resampling
    Enum protocol: sassetti, tn5, mme1

--- Viral Analysis ---

  viral_assembly (API: ViralAssembly)
    Description: Assemble viral genomes from sequencing reads
    Required: output_path, output_file
    Defaults: recipe=auto, viral_size=5M, debug=0
    Enum recipe: auto, irma
    Enum module: FLU, CoV, RSV, EBOLA, FLU_AD

  sars_genome_analysis (API: SARS2Assembly)
    Description: SARS-CoV-2 genome assembly and analysis
    Required: primers, output_path, output_file
    Required (at least one): paired_end_libs | single_end_libs | srr_ids
    Defaults: recipe=auto, primers=ARTIC, min_depth=100, max_depth=8000, keep_intermediates=0, debug_level=0
    Enum recipe: auto, onecodex, cdc-illumina, cdc-nanopore, artic-nanopore
    Enum primers: ARTIC, midnight, qiagen, swift, varskip, varskip-long

  sars_wastewater_analysis (API: SARSWastewaterAnalysis)
    Description: SARS-CoV-2 wastewater surveillance analysis
    Required: primers, output_path, output_file
    Required (at least one): paired_end_libs | single_end_libs | srr_libs
    Defaults: recipe=auto, primers=ARTIC, minimum_base_quality_score=20, minimum_genome_coverage=60, agg_minimum_lineage_abundance=0.01, minimum_coverage_depth=0, confirmedonly=False, minimum_lineage_abundance=0.001, coverage_estimate=10, timeseries_plot_interval=0, sample_metadata_csv=0, keep_intermediates=True, debug_level=0
    Enum recipe: onecodex
    Enum primers: ARTIC, midnight, qiagen, swift, varskip, varskip-long

  influenza_ha_subtype_conversion (API: InfluenzaHASubtypeConversion)
    Description: Influenza HA subtype conversion/classification
    Required: input_source, types, output_path, output_file
    Required (at least one): input_fasta_data | input_fasta_file | input_feature_group | input_feature_list
    Enum input_source: feature_list, fasta_data, fasta_file, feature_group

  subspecies_classification (API: SubspeciesClassification)
    Description: Viral subspecies/clade classification
    Required: input_source, virus_type, output_path, output_file
    Enum input_source: id_list, fasta_data, fasta_file, genome_group

--- Comparative Analysis ---

  comparative_systems (API: ComparativeSystems)
    Description: Compare pathways, subsystems, and protein families across genomes
    Required: output_path, output_file
    Required (at least one): genome_ids | genome_groups
    Defaults: genome_ids=[], genome_groups=[]

--- Submission ---

  sequence_submission (API: SequenceSubmission)
    Description: Submit sequences to public databases
    Required: input_source, metadata, first_name, last_name, email, output_path, output_file
    Enum input_source: id_list, fasta_data, fasta_file, genome_group

--- Utility ---

  date (API: Date)
    Description: Date/time utility service
"""
